<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/ESAA_YB_WEEK1_%ED%95%84%EC%82%AC2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [2]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**read_csv()**: col을 콤마(',')로 구분한 파일 포맷 변환.
- 다른 필드 구분 문자 기반의 파일 포맷도 DataFrame으로 변환 가능. > read_csv('파일명',**sep='\t'**)
- **filepath** 인자: 로드하려는 데이터 파일의 경로를 포함한 파일명 입력.

read_table(): col을 탭('\t')로 구분한 파일 포맷 변환.

read_fwf(): 고정 길이 기반의 칼럼 포맷 로딩.

**read_csv()**

- (파라미터 지정 없을 시) 데이터 파일의 첫 번째 줄에 있던 col 문자열 >  DataFrame의 col 할당
- 콤마(',')로 분리된 데이터값들이 col에 맞게 할당.
- Index 객체 값: 고유의 레코드를 식별하는 역할.

DataFrame: DataFrame의 모든 데이터 표출.

DataFrame.head(): DataFrame의 맨 앞에 있는 N개 row 반환.

In [5]:
titanic_df=pd.read_csv('/content/drive/My Drive/train.csv')
print('titanic 변수 type:',type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

shape(): DataFrame의 행과 열을 튜플 형태로 반환.

info(): 총 데이터 건수, 데이터 타입, Null 건수.
- RangleIndex: DataFrame index의 범위 > 전체 row 수
- Dtype: col별 데이터 타입
- Non-Null Count: 몇 개의 데이터가 Null값이 아닌지
- dtypes: 전체 col의 타입을 요약.

describe(): 칼럼별 숫자형 데이터값의 n-percentile **분포도**, 평균값, 최댓값, 최솟값.
- 숫자형(int, float) 칼럼의 분포도만 조사함. object 타입 제외.
- 계략적인 분포도 확인 가능.

In [7]:
print('DataFrame 크기:',titanic_df.shape)

DataFrame 크기: (891, 12)

In [8]:
titanic_df.info()

# RangleIndex: DataFrame index의 범위 > 전체 row 수
# Dtype: col별 데이터 타입
# Non-Null Count: 몇 개의 데이터가 Null값이 아닌지
# dtypes: 전체 col의 타입을 요약.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
titanic_df.describe()

# count: Null값이 아닌 데이터 건수
# mean: 전체 데이터의 평균값 / std: 표준편차 / min, max: 최솟값, 최댓값
# n%: n percentile 값

# 카테고리 칼럼: 특정 범주에 속하는 값을 코드화한 칼럼 ex. 성별 칼럼

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

DataFrame['칼럼명']: Series 형태로 칼럼 데이터 세트 반환.

value_counts(): 지정된 칼럼의 데이터값 건수 반환. **데이터 분포도** 확인.
- 많은 건수 순서로 정렬.

DataFrame['칼럼명'].value_counts(): 해당 칼럼값의 유형과 건수 반환.

In [10]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [11]:
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

Series: Index와 1개의 col로 구성된 데이터 세트.
- 12.. 0~4 순차 값 = DataFrame의 Index
- 13.. 3, 1, 2 인덱스값: **고유성이 보장된다면** 의미 있는 데이터값 할당 가능.
- 인덱스는 DataFrame, Series가 만들어진 후에도 변경 가능. 숫자형, 문자열 가능.

In [12]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [13]:
value_counts=titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

NULL값을 포함하여 개별 데이터값의 건수를 계산할지를 **dropna 인자**로 판단.
- **dropna**: **기본값 True (NULL값 제외한 뒤 연산.)** / False 지정 시 NULL값을 포함하여 개별 데이터값 건수 계산.

In [14]:
print('titanic_df 데이터 건수:',titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print(titanic_df['Embarked'].value_counts()) # NULL값 제외한 뒤 연산 수행.
print(titanic_df['Embarked'].value_counts(dropna=False)) # NULL값 포함. > False

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

## DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

### 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

DataFrame: 칼럼명 有 (<-> 리스트, 넘파이 ndarray)

DataFrame으로 변환 시 칼럼명 지정 필요. : **pd.DataFrame(data,columns)**
- data: 리스트나 딕셔너리 또는 넘파이 ndarray를 입력.
- columns: 칼럼명 리스트를 입력.

In [15]:
import numpy as np

col_name1=['col1'] # 칼럼명 리스트
list1=[1,2,3] # 리스트
array1=np.array(list1) # 넘파이 ndarray
print('array1 shape:',array1.shape)

# 리스트를 이용해 DataFrame 생성.
df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame;\n',df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1=pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrmae:\n',df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame;
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrmae:
    col1
0     1
1     2
2     3

In [16]:
# 3개의 칼럼명이 필요함.
col_name2=['col1','col2','col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2=[[1,2,3],
       [11,12,23]]
array2=np.array(list2)
print('array2 shape:',array2.shape)
df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n',df_list2)
df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n',df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    23
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    23

In [34]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑.
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

### DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

DataFrame -> ndarray

: array 만들기 **df_dict.values**

DataFrame -> 리스트

: array에 tolist() 호출 **df_dict.values.tolist()**

DataFrame -> 딕셔너리

: DataFrame에 to_dict() 호출 후 인자로 'list' 입력 **df_dict.to_dict('list')**

In [35]:
# DataFrame을 ndarray로 변환.
array3=df_dict.values
print('df_dict.values 타입:',type(array3),'df_dict.values shape:',array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [36]:
# DataFrame을 리스트로 변환.
list3=df_dict.values.tolist()
print('df_dict.values.tolist() 타입:',type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환.
dict3=df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:',type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

## DataFrame의 칼럼 데이터 세트 생성과 수정

In [37]:
# 'Age_0' 칼럼 추가.
titanic_df['Age_0']=0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [38]:
# 기존 칼럼 Series를 가공해 'Age_by_10', 'Family_No' 생성.
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [39]:
# 기존 칼럼 값 일괄 업데이트.
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

## DataFrame 데이터 삭제

drop() 메서드 이용.

DataFrame.drop(**labels=None,axis=0**,index=None,columns=None,level=None,**inplace=False**,errors='raise')

**labels**: 여러 개의 칼럼을 삭제하고 싶을 경우 **리스트** 형태로 삭제하고자 하는 칼럼명을 입력.

**axis**: 특정 칼럼 또는 특정 행을 드롭.
- axis=1 입력 시 **칼럼 드롭** (기존 칼럼 값을 가공 > 새로운 칼럼 생성, 삭제)
- axis=0 입력 시 로우 드롭 (이상치 데이터를 삭제하는 경우)

**inplace**
- 디폴트값 False: 원본 DataFrame 유지, 드롭된 DataFrame을 새롭게 객체 변수로 받을 경우.
- **inplace=True** 원본 DataFrame에 드롭된 결과를 적용할 경우.

In [40]:
# 'Age_0' 칼럼 삭제.
titanic_drop_df=titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [41]:
titanic_df.head(3) # inplace=False

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

In [42]:
drop_result=titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)
print('inplace=True로 drop 후 반환된 값:',drop_result)
titanic_df.head(3)

# titanic_df=titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)는 titanic_df의 객체 변수를 None으로 만듦.

inplace=True로 drop 후 반환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [44]:
# index 0, 1, 2 row 삭제.

pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2],axis=0,inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

## Index 객체

DataFrame, Series에서 Index 객체만 추출하려면 **DataFrame.index, Series.index** 속성을 이용.

- 단일값 반환, 슬라이싱 가능.
- 한 번 만들어진 DataFrame 및 Series의 Index 객체는 변경 불가능.
- Index는 연산에서 제외.

In [46]:
# 원본 파일 다시 로딩
titanic_df=pd.read_csv('/content/drive/My Drive/train.csv')
# Index 객체 추출
indexes=titanic_df.index
print(indexes)
# Index 객체를 실제 값 array로 변환
print('Index 객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [50]:
print(type(indexes.values))
# 1차원 array
print(indexes.values.shape)
# 단일값 반환, 슬라이싱.
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [51]:
# 한 번 만들어진 DataFrame 및 Series의 Index 객체는 변경 불가능.
indexes[0]=5

TypeError: Index does not support mutable operations

In [54]:
series_fair=titanic_df['Fare']
print('Fair Series max 값:',series_fair.max())
print('Fair Series sum 값:',series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fair Series + 3:\n',(series_fair+3).head(3))
# Index는 연산에서 제외.

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

**reset_index()**

인덱스가 연속된 int 숫자형 데이터가 아닐 경우 이를 **연속 int 숫자형 데이터로 만들 때** 사용.

기존 인덱스는 'index'라는 새로운 칼럼명으로 추가. > DataFrame으로 변환.

- **drop=True** 설정 시 기존 인덱스가 새로운 칼럼으로 추가되지 않고 삭제됨.

In [56]:
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [57]:
print('### befor reset_index ###')
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))
new_value_counts=value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

### befor reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

## 데이터 셀렉션 및 필터링

넘파이

'[]' 연산자 내 단일값 추출, 슬라이싱, 팬시 인덱싱, 불린 인덱싱.

**판다스**: **iloc[], loc[]**

### DataFrame의 [] 연산자

넘파이의 [] 연산자

행의 위치, 열의 위치, 슬라이싱 범위 지정.

DataFrame 바로 뒤의 '[]': **칼럼 지정 연산자**만 들어갈 있음.
- 칼럼 지정 연산에 사용.
- 불린 인덱싱 용도로 사용.

In [58]:
print('단일 칼럼 데이터 추출:\n',titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n',titanic_df[['Survived','Pclass']].head(3))
print('[] 안에 숫자 index는 KeyError 오류 발생:\n',titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

In [59]:
titanic_df[0:2] # 인덱스 형태로 변환 가능한 표현식

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [60]:
titanic_df[titanic_df['Pclass']==3].head(3) # 불린 인덱싱도 표현 가능.

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

### DataFrame iloc[] 연산자
: row, col을 지정하여 데이터를 선택할 수 있는 인덱싱 방식.

**iloc[]**: 위치 기반 인덱싱 방식.
- 행과 열 위치를, 0을 출발점으로 하는 세로축, 가로축 좌표 정숫값(또는 정수형의 슬라이싱, 팬시 리스트 값)으로 지정하는 방식.
- **iloc[행 위치 정숫값, 열 위치 정숫값]**
- **열 위치에 -1 입력**: 마지막 열 데이터 가져옴. (iloc[:,-1]: 맨 마지막 칼럼 값, iloc[:,:-1]: 맨 마지막 칼럼 값만 제외한 모든 값.)

loc[]: 명칭 기반 인덱싱 방식.
- 인덱스값으로 행 위치를, 칼럼의 명칭으로 열 위치를 지정하는 방식.

In [62]:
data={'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
      'Year':[2011,2016,2015,2015],
      'Gender':['Male','Female','Male','Male']}
data_df=pd.DataFrame(data,index=['one','two','three','four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [63]:
data_df.iloc[0,0] # iloc[행 위치 정숫값, 열 위치 정숫값]

'Chulmin'

In [64]:
# 아래 코드는 오류를 발생시킵니다.
data_df.iloc[0,'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [65]:
# 아래 코드는 오류를 발생시킵니다.
data_df.iloc['one',0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [73]:
data_df.iloc[1,0] # 2 row 1 col의 단일값 반환.

'Eunkyung'

In [74]:
data_df.iloc[2,1] # 3 row 2 col의 단일값 반환.

np.int64(2015)

In [75]:
data_df.iloc[0:2,[0,1]]
# 0:2 슬라이싱 범위의 1, 2 row와 1, 2 col의 DataFrame 반환.

         Name  Year
one   Chulmin  2011
two  Eunkyung  2016

In [77]:
data_df.iloc[0:2,0:3]
# 0:2 슬라이싱 범위의 1, 2 row와 1, 2, 3 col의 DataFrame 반환.

         Name  Year  Gender
one   Chulmin  2011    Male
two  Eunkyung  2016  Female

In [76]:
data_df.iloc[:] # 전체 DataFrame 반환.

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [78]:
data_df.iloc[:,:] # 전체 DataFrame 반환.

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [79]:
print("\n 맨 마지막 칼럼 데이터 [:,-1] \n",data_df.iloc[:,-1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:,:-1] \n",data_df.iloc[:,:-1])

 맨 마지막 칼럼 데이터 [:,-1]
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:,:-1]
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015

### DataFrame loc[] 연산자

**loc[]**: 명칭 기반 인덱싱 방식.
- 인덱스값으로 행 위치를, 칼럼의 명칭으로 열 위치를 지정하는 방식.
- **loc[인덱스값, 칼럼명]**

In [80]:
data_df.loc['one','Name']

'Chulmin'

In [81]:
# 다음 코드는 오류를 발생시킵니다.
data_df.loc[0,'Name']

KeyError: 0

In [86]:
print('위치기반 iloc slicing\n',data_df.iloc[0:1,0],'\n')
print('명칭기반 loc slicing\n',data_df.loc['one':'two','Name'])

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

In [87]:
data_df.loc['three','Name']
# 인덱스값 three, Name 칼럼의 단일값 반환.

'Jinwoong'

In [88]:
data_df.loc['one':'two',['Name','Year']]
# 인덱스값 one~two, Name, Year 칼럼의 DataFrame 반환.

         Name  Year
one   Chulmin  2011
two  Eunkyung  2016

In [92]:
data_df.loc['one':'three','Name':'Gender']
# 인덱스값 one~three, Name~Gender 칼럼의 DataFrame 반환. (종료점 포함)

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male

In [ ]:
data_df.loc[:] # 모든 데이터 값

In [93]:
data_df.loc[data_df.Year>=2014]
# 불린 인덱싱 가능. Year 칼럼이 2014 이상인 모든 데이터 추출.

           Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

### 불린 인덱싱

In [94]:
titanic_df=pd.read_csv('/content/drive/My Drive/train.csv')
titanic_boolean=titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [95]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [96]:
# loc[] 이용.
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

복합 조건
1. and : '&'
2. or : '|'
3. Not : '~'

In [97]:
# 나이 60세 이상, 선실 등급 1등급, 성별 여성인 승객 추출.
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [98]:
cond1=titanic_df['Age']>60
cond2=titanic_df['Pclass']==1
cond3=titanic_df['Sex']=='female'
titanic_df[cond1 & cond2 & cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

## 정렬, Aggregation 함수, GroupBy 적용

### DataFrame, Series의 정렬 - sort_values()

sort_values()

**by**: 특정 칼럼 입력 시 해당 칼럼으로 정렬 수행.

**ascending**=True(기본값): 오름차순 정렬.
- ascending=False: 내림차순 정렬.

**inplace**=False(기본값): 호출한 DataFrame 유지, 정렬된 DataFrame을 결과로 반환.
- inplace=True: 호출한 DataFrame의 정렬 결과를 그대로 적용.

In [100]:
# Name 칼럼을 오름차순 정렬해 반환.
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [101]:
# Pclass와 Name을 내림차순 정렬해 반환.
titanic_sorted=titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

### Aggregation 함수 적용

Aggregation 함수 - min, max, sum, count 등
- DataFrame에서 바로 aggregation을 호출할 경우 모든 칼럼에 해당 aggregation 적용.

In [102]:
titanic_df.count()
# Null값 반영하지 않은 결과 반환.

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [103]:
titanic_df[['Age','Fare']].mean()
# 특정 칼럼에만 aggregation 함수 적용.

Age     29.699118
Fare    32.204208
dtype: float64

### groupby() 적용

파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby 적용.

aggregation 함수 적용 시 groupby() 대상 칼럼을 제외한 모든 칼럼에 aggregation 적용.
- 필터링 후 필터링 대상 칼럼에만 aggregation 적용.
- 여러 개의 aggregation 함수명을 agg() 내에 인자로 입력.

In [104]:
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [105]:
# aggregation 함수 적용 시 groupby() 대상 칼럼을 제외한 모든 칼럼에 aggregation 적용.
titanic_groupby=titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [106]:
# 필터링 후 필터링 대상 칼럼에만 aggregation 적용.
titanic_groupby=titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [108]:
# 여러 개의 aggregation 함수명을 agg() 내에 인자로 입력.
titanic_df.groupby('Pclass')['Age'].agg([max,min])

/tmp/ipython-input-414103430.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
/tmp/ipython-input-414103430.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [110]:
# agg() 내에 입력값을 딕셔너리 형태로 '칼럼':'aggregation 함수' 입력
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

## 결손 데이터 처리하기

### isna()로 결손 데이터 여부 확인

isna(): 데이터가 NaN인지 아닌지 알려줌.
- 결손 데이터 개수 > isna()에 sum() 추가

In [113]:
titanic_df.isna().head(3)

   PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [114]:
# 결손 데이터 개수 > isna()에 sum() 추가
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### fillna()로 결손 데이터 대체하기

In [116]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [118]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## apply lambda 식으로 데이터 가공

lambda: 함수의 선언과 함수 내의 처리를 한 줄의 식으로 변환하는 식.

map(): lambda 식을 이용할 때 여러 개의 값을 입력 인자로 사용해야 할 경우.

In [119]:
def get_square(a):
  return a**2

print('3의 제곱은:',get_square(3))

3의 제곱은: 9

In [120]:
lambda_square=lambda x : x**2
print('3의 제곱은:',lambda_square(3))

3의 제곱은: 9

In [121]:
a=[1,2,3]
squares=map(lambda x : x**2,a)
list(squares)

[1, 4, 9]

In [122]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

if 절의 경우 if 식보다 반환값을 먼저 기술.

**lambda x: 'if일 때의 반환값' if 조건 else 'else일 때의 반환값'**

In [123]:
# 나이가 15세 미만이면 Child, 아니면 Adult
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [125]:
# else if 사용법
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [126]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성.
def get_category(age):
  cat=''
  if age<=5: cat='Baby'
  elif age<=12: cat='Child'
  elif age<=18: cat='Teenager'
  elif age<=25: cat='Student'
  elif age<=35: cat='Young Adult'
  elif age<=60: cat='Adult'
  else: cat='Elderly'

  return cat

# lambda 식에 위에서 생성한 get_category() 함수를 반환값으로 지정.
# get_category(X)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환.
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult